### ISSUE TITLE
Is this supposed to work with Socket.IO version 4+?

### ISSUE THREAD

**Issue by jcnmsg** [vote539/socketio-file-upload#145]
I have upgraded from Socket.IO 2.x.x to 4.6.1 and it appears to have broken the upload functionality. I'm currently getting `Error: Client disconnected in the middle of an upload at Socket.<anonymous> (./node_modules/socketio-file-upload/server.js:558:14)` but it was working fine prior to upgrading the Socket.IO version.

Is it correct to assume this isn't ready for version 4+? I'd assume this isn't compatible with it given both release dates (March 2021 x December 2020) but thought I'd ask to be sure since the `README.md` mentions 0.9 or higher.

**Comment by jcnmsg** [comment]
For anyone having the same problem, a temporary workaround is to disable the transmission of binary data on the client (and use base64 instead) by setting `instance.useBuffer` to `false`. Re-open if needed.

**Comment by sffc** [comment]
I've been using this with socket.io version 4.5.4 with no known issues. I'll keep an eye out if I see errors like the ones you're seeing.

**Comment by jcnmsg** [comment]
Let me know if you ever bump into it yourself. My previous configuration that was working well was socket.io v2.3.0 across the stack with socketio-file-upload v0.7.2. With 4.6.1/0.7.3 I get that error without using base64.

**Comment by jcnmsg** [comment]
Just checking in to let you know I found the culprit and it wasn't related to sio or siofu. I was using the [eiows npm package](https://www.npmjs.com/package/eiows) which was also upgraded to the latest version but has since been deprecated. Switching to the default sio engine completely fixed the issue.
