### ISSUE TITLE
Binary Data Transmission

### ISSUE THREAD

**Issue by vote539** [vote539/socketio-file-upload#16]
Socket.IO 1.0 now supports binary data transmission through the WebSocket.  The next release of Socket.IO File Upload will support transmitting files through this new architecture.

You can enable file transfer with buffers by setting `instance.useBuffer = true` on the client side.

As you use this new feature, leave feedback here.  In a future release of Socket.IO File Upload, this option may default to "true" rather than to "false".

**Comment by ArtskydJ** [comment]
Since binary data transmission is enabled by default, can this issue be closed?

**Comment by vote539** [comment]
It's been 9 months since this has been on by default, and no one has reported any problems, so it seems like a good time to close the issue.
