### ISSUE TITLE
Support for non-html5 browsers

### ISSUE THREAD

**Issue by selay** [vote539/socketio-file-upload#20]
Hi there, just a quick question. 
I just read the readme file and noticed you mention html5 supporting browsers. 
Is that requirement about file drag-and-drop or for this module to work? 
Given socket.io works in ie7, can we assume this module works in ie7?

**Comment by vote539** [comment]
This module requires support for the [FileReader API](http://caniuse.com/#feat=filereader) and so it won't work in IE 7.
