### ISSUE TITLE
Client gets original file name even the file name has been updated

### ISSUE THREAD

**Issue by andy-h-chen** [vote539/socketio-file-upload#24]
If a file with dupe file name is uploaded, it would be saved as <filename>-0.<ext>, but the client is still notified with the original name.

**Comment by vote539** [comment]
Hi, you can access the updated file name on the client side [in the "progress" and "load" events](https://github.com/vote539/socketio-file-upload#progress).  You can also manually save it into the ["clientDetail" metadata object](https://github.com/vote539/socketio-file-upload#server-to-client-meta-data).  Hope this helps!

**Comment by andy-h-chen** [comment]
Thanks, I'll try.
