### ISSUE TITLE
How would I get access to the data without saving it to disk ?

### ISSUE THREAD

**Issue by zglozman** [vote539/socketio-file-upload#26]
There is a mention in the documentation that it is possible but i can not figure out how to do it. 
if i set  uploader.dir =null any way i can get the raw data?

**Comment by vote539** [comment]
You need to read from the buffer in the "progress" event.  To get the whole file, you can just append to some other variable.  For example,

```
var fullContent = "";
uploader.on("progress", function(event){
	fullContent += event.buffer;
});
uploader.on("saved", function(event){
	// do something with the file
	console.log("All done");
});
```

Hope that helps.

**Comment by zglozman** [comment]
Yes very much thank you

Sent from my iPhone

On Jun 26, 2015, at 11:36 AM, vote539 <notifications@github.com> wrote:

You need to read from the buffer in the "progress" event. To get the whole
file, you can just append to some other variable. For example,

var fullContent = "";
uploader.on("progress", function(event){
    fullContent += event.buffer;
});
uploader.on("saved", function(event){
    // do something with the file
    console.log("All done");
});

Hope that helps.

—
Reply to this email directly or view it on GitHub
<https://github.com/vote539/socketio-file-upload/issues/26#issuecomment-115574960>
.
