### ISSUE TITLE
Can't upload file in Android Crosswalk when use plugin File or File-transfer

### ISSUE THREAD

**Issue by ngohuynhngockhanh** [vote539/socketio-file-upload#29]
Hello vote539,

Have a nice day!

I have found a bug in hybrid mobile app that makes the socketio-file-upload don't work. 

When I add plugin org.apache.cordova.file or org.apache.cordova.file-transfer to my app (ionic crosswalk android app), I can't upload my file to server but can choose file.

After some researchs (compared between Android and Firefox browser in Dekstop,... ), I found that the FileReader object in Android crosswalk has quite differences, it was changed by default, but you can find an attribute "_realReader"!

Yeah, from that point, I add following lines before line "// Calculate chunk size" and it works :)
```
if (reader._realReader)
		reader = reader._realReader;
```
Thank for your awesome plugin!

**Comment by vote539** [comment]
Thanks for the comment, ngohuynhngockhanh!  Would you like to submit a pull request with this change?  I'll happily merge it if you do.
