### ISSUE TITLE
Clear input value after upload

### ISSUE THREAD

**Issue by yene** [vote539/socketio-file-upload#40]
`input` does not trigger change event when the value is the same. To upload the same file twice the input value has to be cleared.

**Comment by MaffooBristol** [comment]
Unfortunately I think this is just an issue with the way that browsers naturally handle change events in file inputs. Even if you do it with plain Javascript or jQuery, you'll get no `change` event when selecting the same file. So yeah, at the moment my only suggestion would be to clear the value after every upload. Is there any major issue with doing that?

**Comment by yene** [comment]
No

**Comment by MaffooBristol** [comment]
Glad I could help.

**Comment by vote539** [comment]
Actually I have experienced this issue myself, and agree that it would be convenient if SIOFU took care of clearing the input field, especially for the black-box `siofu.prompt()` implementation.  I'm going to reopen the issue.

**Comment by vote539** [comment]
I made a pull request that implements an auto-reset feature.  Let me know if you like it and then I'll merge it into master.

**Comment by vote539** [comment]
Closed by #45
