### ISSUE TITLE
Rename File on Complete of Upload ?

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#43]
Is there a method to handle this on complete promise to rename file?

**Comment by MaffooBristol** [comment]
How about just [fs.rename()](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback)...?

Or any of the methods in [fs-extra](https://github.com/jprichardson/node-fs-extra).

Unless I'm missing something, I don't see how this is related directly to this module.

**Comment by vote539** [comment]
@MaffooBristol's code is how I'd recommend doing this.  There is no out-of-the-box support for "promises" right now.  (Thanks @MaffooBristol for posting the example!)
