### ISSUE TITLE
Upload Interruption should trigger error for handling  

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#46]
When client socket disconnects or refresh happens on client side there should be an error on server. Is this the case? did I miss something in the documentation?
on.complete does not fire when file is upload is interrupted.

**Comment by vote539** [comment]
This is an excellent edge case that hadn't been considered before.  I just added a feature in a branch that emits an "error" event if a client disconnects during an active upload (see my commit above).  Does that seem like reasonable behavior?

**Comment by LeoCreer** [comment]
YES !!!

**Comment by LeoCreer** [comment]
When incoming upload stops before it has finished I would like to do 1 of 2 things.

1. handle error and delete incomplete file.

2. handle error store upload id and user id and pick upload back up from where it left off.

**Comment by vote539** [comment]
Closed by #45.

This hook should be sufficient for now.  The more specific functionality you need, at least (1), can be implemented separately.  Suggestion (2) is a really good idea but it would probably require a larger architectural change.
