### ISSUE TITLE
Drag Events

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#49]
listenOnDrop() does this method override the drop event.

**Comment by MaffooBristol** [comment]
Could you further explain what you mean please?

**Comment by vote539** [comment]
The code is simple; it just adds a binding to the "dragover" and "drop" events.

https://github.com/vote539/socketio-file-upload/blob/master/client.js#L424

`event.preventDefault()` is called on both events, but not `event.stopPropagation()`.
