### ISSUE TITLE
Invoke upload without Submit or Drop event 

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#50]
is there a way to invoke event upload with outside of ... listenOnSubmit / listenOnDrop ?

**Comment by MaffooBristol** [comment]
Are you possibly looking for [`instance.submitFiles(files)`](https://github.com/vote539/socketio-file-upload#instancesubmitfilesfiles)?

**Comment by LeoCreer** [comment]
Yes thank you
