### ISSUE TITLE
submitFiles() should accept objects of type `File` or an array of `Files`, not just FileList

### ISSUE THREAD

**Issue by MaffooBristol** [vote539/socketio-file-upload#51]
I'm bouncing the output from [Dropzone.js](http://www.dropzonejs.com/) and specifically [react-dropzone](https://github.com/okonet/react-dropzone) into SIOFU's `instance.submitFiles()`, but it seems to only accept objects of type FileList, whilst dropzone's onDrop events pass through a File, meaning that it's not compatible. I thought perhaps I could send the File array-wrapped, or even instantiate a `new FileList([File])` or something, but that seems to not be supported. Some things when sent will chuck out an error, but some things will just silently fail. On the whole it seems to be a bit confusing as to how exactly it should work.

What are your thoughts on this?

Ta!
Matt

**Comment by MaffooBristol** [comment]
Actually, nevermind, I think it is working as expected.

**Comment by vote539** [comment]
👍

**Comment by MaffooBristol** [comment]
I still think the documentation could be cleaned up a little bit, as it turns out it doesn't require a FileList at all. Especially because generally it's not very easy to find out anything about the `File` and `FileList` types, at least from my searches. Can they even be instantiated manually? Is an array of `File`s equal to a `FileList` of `File`s??

**Comment by vote539** [comment]
Updated the README.  Thanks for the suggestion 👍 

According to the MDN, a FileList just seems to be an array-like, immutable object, similar maybe to the infamous *arguments* variable that gives you some subset of the normal array operations.

**Comment by MaffooBristol** [comment]
Nice one man, thanks! :)
