### ISSUE TITLE
Manually invoke upload instance.submitFiles(files)

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#53]
Hi 
I'm trying to drag a image from element on the screen or from a remote URL into drop element of siofu. Manually invoke upload am I going down the right path or is there a different way to handle this ?
```
 angular.element(currentElement).bind('drop',function(event){
      var imageURL = event.dataTransfer.getData('text');
      var xhr = new XMLHttpRequest();
      xhr.open('GET', imageURL, true);
      xhr.responseType = 'blob';
      xhr.onload = function(e) {
      if (this.status === 200) {
         var myBlob = xhr.response;
         var fileObj = new File([myBlob],'image.jpg',{});
         siofu.submitFiles(fileObj);
      }
  };
```

**Comment by LeoCreer** [comment]
instance.submitFiles(files)  There is not enough info on this in the DOC.

**Comment by MaffooBristol** [comment]
Hi leo, you're missing a closing brace in your code but I don't imagine that's relevant.

Can I ask what your reason for using SIOFU is in this example if you're getting the file via an xhr request? SIOFU is meant to work with files sent via the browser file input. Is your code currently working for you or not?

**Comment by vote539** [comment]
XHR can't perform cross-domain requests.  This pattern is not currently possible.  Allowing file input from a remote URL is one of the items on the to-do list at the bottom of SIOFU's readme.

**Comment by LeoCreer** [comment]
I'm trying to 
get a file from inside client DOM that has drag=true on element 
drag image onto siofu 
upload file.

**Comment by MaffooBristol** [comment]
If that's the case, what's the xhr request about?

**Comment by LeoCreer** [comment]
My original approach was to get the physical file and then send it but I guess that  is not the right way considering the circumstances.

**Comment by MaffooBristol** [comment]
Ah yes, well being able to send a buffer is definitely a feature that would be useful, but as vote said, that's very much a future todo at the moment. I imagine it would be relatively time consuming but not impossible to implement, but for now it's not capable of that! Sorry

**Comment by LeoCreer** [comment]
Thanks
