### ISSUE TITLE
File mtime detected as invalid.

### ISSUE THREAD

**Issue by DaneEveritt** [vote539/socketio-file-upload#57]
I'm having a strange issue where file uploads are being marked as having an invalid `mtime` when they are uploaded. This causes the files to use UNIX epoch as the timestamp (which is a bit undesirable).

This is an example of the output of the `saved` event on the server.
```
{ file: 
   { name: 'Microsoft Word - Lab 5 Lists.pdf',
     mtime: Invalid Date,
     encoding: 'octet',
     clientDetail: {},
     meta: { path: '', identifier: 'vqrn05pdn7m' },
     id: 0,
     size: 72118,
     bytesLoaded: 72118,
     success: true,
     base: 'Microsoft Word - Lab 5 Lists',
     pathName: '/srv/daemon-data/ptdl-mumble_e1ltb/data/Microsoft Word - Lab 5 Lists.pdf',
     writeStream: 
      WriteStream {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        path: '/srv/daemon-data/ptdl-mumble_e1ltb/data/Microsoft Word - Lab 5 Lists.pdf',
        fd: 20,
        flags: 'w',
        mode: '0666',
        start: undefined,
        autoClose: true,
        pos: undefined,
        bytesWritten: 72118 } } }
```

Here is the output of `event.file` during the progress step in the browser.
```
lastModified: 1476111825000
meta: {path: "", identifier: "vqrn05pdn7m"}
name: "Microsoft Word - Lab 5 Lists.pdf"
size: 72118
type: "application/pdf"
```

Same output on the `complete` event in the browser.
```
lastModified: 1476111825000
meta: {path: "", identifier: "vqrn05pdn7m"}
name: "Microsoft Word - Lab 5 Lists.pdf"
size: 72118
type: "application/pdf"
```

Interestingly, if you refresh the page before the file is done uploading the last modified time is correct.

**Comment by DaneEveritt** [comment]
Appears when the file is saved it shows up as this when you run `ls -l`:

```
-rw-r--r-- 1 user group  5987302 -9223372036854775808 Sea Turtles.docx
```

**Comment by vote539** [comment]
Interesting.  SIOFU gets the mtime information [from file.lastModifiedDate](https://github.com/vote539/socketio-file-upload/blob/master/client.js#L264).  However, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate), "lastModifiedDate" is deprecated.  I wonder if replacing "lastModifiedDate" with "lastModified" would fix the problem?  On the server side, all that happens is that the value gets passed to a new Date() constructor.

Would you mind making this patch and see if it fixes your problem?  Just go into client.js or client.min.js, search for "lastModifiedDate", and replace it with "lastModified".  Thanks!

**Comment by DaneEveritt** [comment]
Sure thing, I'll test that out later, and if it works I'll submit a PR.
