### ISSUE TITLE
Renaming your file before saving

### ISSUE THREAD

**Issue by johadi10** [vote539/socketio-file-upload#66]
maybe i don't understand how this package works very well. i have spent time to see how i can rename a file before saving it to a folder but couldn't figure it out. please if there is  way to achieve this let me know. will be glad to hear your feedback ,thanks

**Comment by vote539** [comment]
There are two easy ways to do this.  You can make your own WriteStream:

```javascript
io.sockets.on("connection", function(socket){
    var uploader = new SocketIOFileUpload();
    uploader.listen(socket);

    var streams = {};
    uploader.on("start", function(event){
        streams[event.file.id] = fs.createWriteStream("<path to where to save>");
    });
    uploader.on("progress", function(event){
        streams[event.file.id].write(event.buffer);
    });
    uploader.on("complete", function(event){
        streams[event.file.id].end();
        delete streams[event.file.id];
    });

    uploader.on("error", function(event){
        console.log("Error from uploader", event);
    });
});
```

The other option is to just move the file (`fs.rename`) after it is finished uploading.

Hope this helps!
