### ISSUE TITLE
complete event triggers multiple times

### ISSUE THREAD

**Issue by maheshWebkul721** [vote539/socketio-file-upload#71]
I have multiple element with same class, i am using knockout data-binding 

template like: 

`<input data-bind="event:{ change: selectFile.bind()}" type="file" name="attachments" class="msg-attachment">
<input data-bind="event:{ change: selectFile.bind()}" type="file" name="attachments" class="msg-attachment">
`

`selectFile: function (e) {
                var socket = io.connect();
                var uploader = new SocketIOFileUpload(socket);
                
                uploader.addEventListener("start", function(event){
                    console.log(event);
                });

                uploader.addEventListener("progress", function(event){
                    console.log(event);
                });

                uploader.addEventListener("complete", function(event){
                    console.log(event);
                });

                siofu.listenOnInput(e.currentTarget);
}`

when i select file first time complete event occurs once, when select decond time its occurs twice ans so on.

Can somebody help me in this case.

**Comment by sffc** [comment]
Your SocketIOFileUpload should be a singleton.  Create it in your main function, not in a callback event.  Then, in your knockout binding, you should use [uploader.submitFiles()](https://github.com/vote539/socketio-file-upload#instancesubmitfilesfiles) directly.
