### ISSUE TITLE
Upload two or more files independently

### ISSUE THREAD

**Issue by Adser89** [vote539/socketio-file-upload#75]
Hi, sorry this is not an issue but, i didn't   know where to address my question specifically.
Following your example i can upload one file using the method presented. However, what will be considered a good practice if i need to upload two files (different formats) in two different moments. 
my issue is regarding that the first file will be send to a folder and the the second to a different one. however when i try to do it. The package cant differentiate between the two inputs and it seems that the outputs get mixed. 

Can you point me in the right direction here please. Thanks in advance

**Comment by sffc** [comment]
Multiple files can be uploaded at the same time.  Files should never get "mixed" as long as you instantiate the SIOFU instances as documented in the readme: one instance per socket connection on the server, and one instance per browser session on the client.
